spring.application.name=rag-java-lab

spring.datasource.url=jdbc:postgresql://localhost:55432/ragdb
spring.datasource.username=raguser
spring.datasource.password=ragpass
spring.datasource.driver-class-name=org.postgresql.Driver
rag.storage.root=storage
rag.chunk.size=500
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

ollama.base-url=http://localhost:11434
ollama.embedding-model=nomic-embed-text
ollama.chat-model=llama3.2